// API/building/post.js
import express from 'express';
import supabase from '../../config/supabaseClient.js';

const router = express.Router();

router.post('/', async (req, res) => {
  // Extract building data from request body
  // 'id' is auto-generated by Supabase (as primary key)
  const { name, status, cost, lvl, user_id } = req.body;

  // Validate required fields
  if (!name || !user_id) {
    return res.status(400).send({ error: 'Missing required fields: name and user_id' });
  }

  try {
    const { data, error } = await supabase
      .from('building')
      .insert([
        { name, status, cost, lvl, user_id }
      ])
      .select(); // .select() returns the newly created record

    if (error) throw error;

    // Send back the newly created building data
    res.status(201).send(data[0]);
  } catch (error) {
    console.error('Error creating building:', error.message);
    res.status(500).send({ error: error.message });
  }
});

export default router;